### ISSUE TITLE
한글 Encoding Issue

### ISSUE THREAD

**Issue by InmookJeong** [cheekee/studymeet#3]
DB(MySQL)에 테스트 데이터를 Insert 해봤는데 한글이 '??'로 저장되고있습니다.
UTF-8 또는 EUC-KR 중 선택하여 한글 인코딩을 맞출 필요가 있을 것 같습니다.

**Comment by cheekee** [comment]
인코딩 UTF-8로 진행할 건데요.
아마도 제가 MYSQL 설치하고 인코딩 설정 안한 것 같아요.
오늘저녁에 설정하고 이 이슈 클로즈 할게요.
테스트는 일단 DB에 직접 입력해서 하시어요.
